return
{
	["result"]= {
		{
			['idx'] = '1',
			['BatteryLevel'] = 10,
			['SignalLevel'] = '10',
			['SubType'] = 'Zone',
			['Type'] = 'Heating',
			['HardwareName'] = 'hw1',
			['HardwareType'] = 'ht1',
			['HardwareID'] = 1,
			['HardwareTypeVal'] = 1,
			['SwitchType'] = 'Contact',
			['SwitchTypeVal'] = 2,
			['Name'] = 'Name1',
			['Data'] = 'On',
			['Status'] = 'On'
		},
		{
			['idx'] = '2',
			['BatteryLevel'] = 20,
			['SignalLevel'] = '20',
			['SubType'] = 'Lux',
			['Type'] = 'Lux',
			['HardwareName'] = 'hw2',
			['HardwareType'] = 'ht2',
			['HardwareID'] = 2,
			['HardwareTypeVal'] = 2,
			['SwitchType'] = "Motion Sensor",
			['SwitchTypeVal'] = 8,
			['Name'] = 'Name2',
			['Data'] = '1;2;3',

		},
		{
			['idx'] = '3',
			['BatteryLevel'] = 30,
			['SignalLevel'] = '30',
			['SubType'] = 'Energy',
			['Type'] = 'P1 Smart Meter',
			['HardwareName'] = 'hw3',
			['HardwareType'] = 'ht3',
			['HardwareID'] = 3,
			['HardwareTypeVal'] = 3,
			['SwitchType'] = 'On/Off',
			['SwitchTypeVal'] = 0,
			['Name'] = 'Name3',
			['Data'] = 'On',
			['Status'] = 'On'
		},
		{
			['idx'] = '4',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'SetPoint',
			['Type'] = 'Thermostat',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
			['Name'] = 'Name4',
			['Data'] = 'On'
		},
		{
			['idx'] = '5',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'kWh',
			['Type'] = 'General',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
			['Name'] = 'Name5',
			['Data'] = '3;3;3;3',
		},
		{
			["Data"] = 'On',
			["LastUpdate"]= "2016-01-29 15:45:52",
			["Name"]= "Scene1",
			["Status"]= "On",
			["Type"]= "Scene",
			["TypeImg"]= "scene",
			["idx"]= "1"
		},
		{
			["Data"] = 'Off',
			["LastUpdate"]= "2016-01-29 15:45:52",
			["Name"]= "Scene2",
			["Status"]= "On",
			["Type"]= "Scene",
			["TypeImg"]= "scene",
			["idx"]= "2"
		},
		{
			["Data"]= "Mixed",
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Group1",
			["Status"]= "Mixed",
			["Type"]= "Group",
			["idx"]= "3"
		},
		{
			["Data"]= "On",
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Group2",
			["Status"]= "On",
			["Type"]= "Group",
			["idx"]= "4"
		},
		{
			["Data"]= "Blah",
			["LastUpdate"]= "2016-04-09 23:17:21",
			["Name"]= "Text1",
			["Status"]= "Blah",
			["Type"]= "General",
			["SubType"]= "Text",
			["idx"]= "6"
		},
	}
}
