return
{
	["result"]= {
		{
			['idx'] = '1',
			['BatteryLevel'] = 10,
			['SignalLevel'] = '10',
			['SubType'] = 'Zone',
			['Type'] = 'Heating',
			['HardwareName'] = 'hw1',
			['HardwareType'] = 'ht1',
			['HardwareID'] = 1,
			['HardwareTypeVal'] = 1,
			['SwitchType'] = 'Contact',
			['SwitchTypeVal'] = 2,
		},
		{
			['idx'] = '2',
			['BatteryLevel'] = 20,
			['SignalLevel'] = '20',
			['SubType'] = 'Lux',
			['Type'] = 'Lux',
			['HardwareName'] = 'hw2',
			['HardwareType'] = 'ht2',
			['HardwareID'] = 2,
			['HardwareTypeVal'] = 2,
			['SwitchType'] = "Motion Sensor",
			['SwitchTypeVal'] = 8,
		},
		{
			['idx'] = '3',
			['BatteryLevel'] = 30,
			['SignalLevel'] = '30',
			['SubType'] = 'Energy',
			['Type'] = 'P1 Smart Meter',
			['HardwareName'] = 'hw3',
			['HardwareType'] = 'ht3',
			['HardwareID'] = 3,
			['HardwareTypeVal'] = 3,
			['SwitchType'] = 'On/Off',
			['SwitchTypeVal'] = 0,
		},
		{
			['idx'] = '4',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'SetPoint',
			['Type'] = 'Thermostat',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
		},
		{
			['idx'] = '5',
			['BatteryLevel'] = 40,
			['SignalLevel'] = '-',
			['SubType'] = 'kWh',
			['Type'] = 'General',
			['HardwareName'] = 'hw4',
			['HardwareType'] = 'ht4',
			['HardwareID'] = 4,
			['HardwareTypeVal'] = 4,
			['SwitchType'] = 'Security',
			['SwitchTypeVal'] = 0,
		}
	}
}
